source 'https://rubygems.org'

ruby '3.4.5'

gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'sqlite3', '~> 1.4'

# Gemfile
gem 'byebug'
gem 'devise'
gem 'devise-jwt'
gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'
gem 'google-api-client', '~> 0.53'
gem 'google-apis-calendar_v3'
gem 'google-id-token'
gem 'omniauth-google-oauth2'
gem 'prawn'
gem 'rack-cors', require: 'rack/cors'
gem 'redis'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'slim-rails'
gem 'csv'
gem 'fiddle'
gem 'httparty' 

# gem 'wicked_pdf'
# gem 'letter_opener_web', group: :development

gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'rspec-rails'
  gem 'shoulda-matchers', '~> 6.0'
end

group :development do
  gem 'letter_opener_web'
  gem 'rubocop',require: false
  gem 'rubocop-rails',require: false 
end
